"""empty message

Revision ID: 3667c07498a1
Revises: 
Create Date: 2024-02-20 12:42:38.480248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3667c07498a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('u_fullname', sa.String(length=128), nullable=False))
        batch_op.drop_column('u_lastname')
        batch_op.drop_column('u_firstname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('u_firstname', mysql.VARCHAR(length=128), nullable=False))
        batch_op.add_column(sa.Column('u_lastname', mysql.VARCHAR(length=128), nullable=False))
        batch_op.drop_column('u_fullname')

    # ### end Alembic commands ###
